version: 0.2
 
phases:
  build:
    commands:
      - echo "Validating deployment files"
      - test -f index.html
      - test -f appspec.yml
      - test -f scripts/install_app.sh
 
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/install_app.sh
  discard-paths: no 
